on:
  push:
    branches:
      - sat

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Atualizado para a versão mais recente
      
      - name: Set up JDK 17  # Mudei para Java 17 conforme sua solicitação anterior
        uses: actions/setup-java@v2  # Atualizado para a versão mais recente
        with:
          java-version: '17'  # Atualizado para Java 17

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
