on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: ["sat"]
    types:
      - completed

jobs:
  promote-to-main:
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git merge sat
          git push origin main
