on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: ["sat"]
    types:
      - completed

jobs:
  promote-to-main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git config --global user.name "WesleySardi"
          git config --global user.email "wesley.sardi@gmail.com"
          git checkout main
          git merge sat
          git push origin main
